a:27:{i:28;a:7:{s:7:"id_news";s:2:"28";s:10:"title_news";s:5:"Акция";s:9:"desc_news";s:1665:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/04/18/c1ab9c1f_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font color="#0000EE"><strong class="bb">Добрый вечер, друзья!</strong>
<br />&nbsp;<br />
Трех-дневная акция для вас, для желающих быстро подняться по карьерной лестнице.
<br />&nbsp;<br />
Разместите <u class="bb">1 ссылку минимум на 1000 просмотров в динамическом VIP серфинге</u>, либо в баннерном VIP серфинге, или в VIP серфинге YouTube <strong class="bb">получите в подарок 2000 баллов рейтинга и бесплатное размещение на 40 дней вашего баннера любого размера из имеющихся на сайте</strong>.
<br />&nbsp;<br />
Закажите <u class="bb">1 ссылку минимум на 2000 просмотров по 20 сек. в динамическом серфинге</u>, <strong class="bb">получите в подарок 2500 баллов рейтинга и размещение вашего баннера любого размера из имеющихся на сайте на 60 дней бесплатно.</strong>
<br />&nbsp;<br />
<i class="bb">Получение подарков по этой акции будет действовать до 21 апреля 18.00 по времени сервера.<br />
<strong class="bb">За каждую ссылку - подарки + за каждые полные потраченные 10 руб. автоматически начисляется по 150 баллов рейтинга, в итоге баллов будет гораздо больше при участии в этой акции.</strong><br />
После заказа пришлите по внутренней почте на логин Znata ссылки на баннер и получите ваши бонусы за активное участие в жизни проекта.</i>
<br />&nbsp;<br />
<strong class="bb">Желающие быстро подняться по карьерной лестнице, принимайте участие и взлетайте!
<br />&nbsp;<br />
Желаем вам отличного весеннего настроения!
<br />&nbsp;<br />
С уважением, Администрация сайта!</strong></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=198#post-19162";s:13:"comments_news";s:1:"0";s:20:"comments_news_status";s:1:"0";s:9:"time_news";s:10:"1555593602";}i:27;a:7:{s:7:"id_news";s:2:"27";s:10:"title_news";s:5:"Акция";s:9:"desc_news";s:2269:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/04/12/SKORPION-12&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font color="3366FF"><strong class="bb">Добрый вечер, друзья!</strong>
<br />&nbsp;<br />
<i class="bb"><strong class="bb">Объявляем о Теплых выходных на ScorpionBux.info!<br />
Весенние дни всё длиннее и теплее, появляется зеленая трава, скоро лето.<br />
Получите тепло и на нашем сайте!<br />
Будьте с нами в эти дни!</strong></i></font></div>
<br />
<div class="bb" align="center"><font color="3366FF">Для вас -</font> </div>
<br />
<font color="3366FF">Конкурс по размещению ссылок в серфинге - <strong class="bb">призы увеличены в два раза.</strong><br />
1 место: 20.00 руб.[осн.счет] + 20.00 руб.[рекл.счет] + 400 баллов<br />
подробности на этой странице <a href="https://scorpionbux.info/konkurs&#063;type=serf" target="_blank">https://scorpionbux.info/konkurs&#063;type=serf</a><br />
Участвуйте - повышайте свой рейтинг и возвращайте потраченные средства с выгодой.
<br />&nbsp;<br />
Просмотр ссылки в серфинге: <strong class="bb">+0.40</strong> балла<br />
Просмотр видеоролика в серфинге YouTube: <strong class="bb">+0.40</strong> балла<br />
Выполнение задания рекламодателя: <strong class="bb">+50.00</strong> баллов<br />
Прохождение теста: <strong class="bb">+5.00</strong> баллов<br />
Привлечение реферала:<strong class="bb"> +30.00 </strong>балла<br />
За каждое размещение аватара на доске почёта:<strong class="bb"> +25.00</strong> баллов<br />
За каждые полные 10 руб потраченные на оплату рекламы с рекламного счета [кроме оплаты заданий и тестов]: <strong class="bb">+350.00</strong> баллов
<br />&nbsp;<br />
За размещение VIP-ссылки в серфинге: <strong class="bb">+150.00</strong> баллов<br />
За размещения VIP-баннера в серфинге: <strong class="bb">+150.00 </strong>баллов<br />
За размещение VIP-ролика в серфинге YouTube: <strong class="bb">+150.00</strong> баллов </font>
<br />&nbsp;<br />
<div class="bb" align="center"><font color="3366FF"><strong class="bb">Теплого вечера вам и приятных выходных дней, друзья! <br />
<i class="bb">Наше предложение будет действовать до 14 апреля 18.00 по времени сервера.</i><br />
С уважением, Администрация сайта.</strong></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=197#post-19016";s:13:"comments_news";s:1:"1";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1555081632";}i:26;a:7:{s:7:"id_news";s:2:"26";s:10:"title_news";s:13:"Нам 3 месяца!";s:9:"desc_news";s:3530:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/04/08/SKORPION-8&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="3"><font color="#8B0A50"><strong class="bb">Добрый день, друзья!<br />
У нас маленькая дата - 3 месяца в сети!</strong><br />
На данный момент на сайте зарегистрировано более 9700 пользователей,<br />
выплачено более 84 тыс. рублей.<br />
Не обошлось без трудностей, как и всегда бывает в начале работы новых проектов, но все проблемы решаемы и надо верить в лучшее.<br />
Сайт в сети и будет продолжать свою работу, преодолевать все невзгоды и проблемы.<br />
Мы с вами и будем с вами!<br />
Больше веры и все будет ХОРОШО!!</font></font></div>
<br />&nbsp;<br />
<font color="#8B0A50">Хоть мы немного и опоздали с празднованием, но все же в честь дня рождения для вас -
<br />&nbsp;<br />
<strong class="bb">Всем снова доступен Тест-драйв на 200 просмотров.</strong>
<br />&nbsp;<br />
Привлечение реферала:<strong class="bb"> +50.00</strong> балла<br />
Выполнение задания рекламодателя: <strong class="bb">+40.00</strong> баллов<br />
За каждое размещение аватара на доске почёта: <strong class="bb">+30.00</strong> баллов<br />
За каждые полные 10 руб потраченные на пополнение копилки + <strong class="bb">150 баллов</strong> рейтинга<br />
За размещение VIP-ссылки в серфинге: <strong class="bb">+200.00</strong> баллов<br />
За размещения VIP-баннера в серфинге: <strong class="bb">+200.00</strong> баллов<br />
За размещение VIP-ролика в серфинге YouTube: <strong class="bb">+200.00</strong> баллов<br />
За каждые полные 10 руб потраченные на оплату рекламы с рекламного счета [кроме оплаты заданий и тестов]: <strong class="bb">+250.00</strong> балла
<br />&nbsp;<br />
Так же специальное предложение для рекламодателей -<br />
Закажите динамический серфинг от <strong class="bb">3000</strong> просмотров по <strong class="bb">20 сек.</strong> и более, мы вам <strong class="bb">в подарок добавим 1000 просмотров этой ссылки дополнительно</strong>.<br />
Напишите на логин Znata по внутренней почте после заказа и получите свой подарок еще 1000 просмотров заказанной вами ссылки.
<br />&nbsp;<br />
<strong class="bb">Скидки :</strong>
<br />&nbsp;<br />
Быстрые сообщения&nbsp;&nbsp;<del class="bb">1.10</del> руб. = 0.90 руб.<br />
Текстовые объявления <del class="bb">1</del> руб. = 0.50 руб. в сутки<br />
Статические ссылки <del class="bb">3.30</del> руб. = 2.50 руб. в сутки<br />
Пакеты рекламы № 4 <del class="bb">180</del> руб. = 150 руб.
<br />&nbsp;<br />
<strong class="bb">Призы и скидки будут действовать с 8 апреля по 11 апреля до 18.00 по времени сервера.<br />
Успейте воспользоваться нашим предложением!</strong>
<br />&nbsp;<br />
<i class="bb"><strong class="bb">Так же напоминаем, что пользователь с ID 10000 и реферер пригласивший его получат приз -<br />
1000 баллов и 10 руб. на рекламный счет пользователю с id 10000 и его рефереру 2000 баллов рейтинга и 50 руб. на рекламный счет.<br />
В случае, если 10000 пользователь не активирует свой аккаунт и не проявит активность на сайте, призовые условия перейдут следующему пользователю под id 10001 и его рефереру.</strong> </i></font>
<br />&nbsp;<br />
<div class="bb" align="center"><font color="#8B0A50"><strong class="bb">Благодарим вас всех за понимание, терпение и поддержку!<br />
Спасибо, что вы с нами!!!<br />
От души благодарим и надеемся на долговременное сотрудничество!
<br />&nbsp;<br />
С уважением, Администрация сайта ScorpionBux.info!</strong></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=196#post-18824";s:13:"comments_news";s:1:"1";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1554728583";}i:25;a:7:{s:7:"id_news";s:2:"25";s:10:"title_news";s:13:"Весенняя пора";s:9:"desc_news";s:2149:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/04/06/SKORPION-6&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font color="006600"><i class="bb"><strong class="bb">Весна, весна! как воздух чист!<br />
Как ясен небосклон!<br />
Своей лазурию живой<br />
Слепит мне очи он.
<br />&nbsp;<br />
Весна, весна! как высоко<br />
На крыльях ветерка,<br />
Ласкаясь к солнечным лучам,<br />
Летают облака!</strong>...</i><br />
<i class="bb">(автор - Е. Баратынский)</i></font></div>
<br />
<div class="bb" align="center"><font color="993399"><strong class="bb">Добрый день, друзья!
<br />&nbsp;<br />
В этот прекрасный весенний день для вас -</strong></font></div>
<br />
<font color="006600"><strong class="bb">Скидка на заказ баннеров-</strong><br />
баннер 468x60 - <strong class="bb">0.85 руб.</strong> в сутки<br />
баннер 468x60 во фрейме -<strong class="bb"> 0.85 руб.</strong> в сутки<br />
баннер 200x300 - <strong class="bb">0.85 руб.</strong> в сутки<br />
баннер 100x100 - <strong class="bb">0.85 руб.</strong> в сутки<br />
баннер 728x90 - <strong class="bb">1 руб.</strong> в сутки
<br />&nbsp;<br />
Выполнение задания рекламодателя: <strong class="bb">+20.00</strong> баллов<br />
Привлечение реферала: <strong class="bb">+35.00</strong> баллов<br />
За каждое размещение аватара на доске почёта: <strong class="bb">+25.00</strong> баллов<br />
За каждые полные 10 руб одним платежом потраченные на оплату рекламы с рекламного счета (кроме заданий и тестов): <strong class="bb">+250.00</strong> баллов<br />
За размещение VIP-ссылки в серфинге: <strong class="bb">+150.00</strong> баллов<br />
За размещения VIP-баннера в серфинге: <strong class="bb">+150.00</strong> баллов<br />
За размещение VIP-ролика в серфинге YouTube: <strong class="bb">+150.00</strong> баллов
<br />&nbsp;<br />
Это предложение действует до 7 апреля 18.00 ч. по времени сервера. </font>
<br />&nbsp;<br />
<div class="bb" align="center"><font color="993399"><strong class="bb">Желаем вам отличного настроения и приятных выходных дней!
<br />&nbsp;<br />
С уважением, Администрация сайта.</strong></font><br />
</div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=195#post-18791";s:13:"comments_news";s:1:"2";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1554552460";}i:24;a:7:{s:7:"id_news";s:2:"24";s:10:"title_news";s:11:"С 1 апреля!";s:9:"desc_news";s:1427:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/04/01/f7ad7138_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="3"><font color="006600"><strong class="bb">Дорогие друзья!<br />
С днем юмора и веселья!<br />
Пусть он подарит вам улыбку и много радости!<br />
Желаем вам в первый день апреля - безграничного веселья!<br />
Верьте, всё будет ХОРОШО! </strong><br />
</font></font></div>
<br />
<div class="bb" align="center"><font size="3"><font color="FF0000"><strong class="bb">От нас в честь 1 апреля - нешуточное предложение!!!</strong><br />
<strong class="bb">Быстрый карьерный рост для всех желающих!</strong></font></font></div>
<br />
<div class="bb" align="center"><font color="990000">Закажите VIP серфинг либо баннерный VIP серфинг, либо VIP серфинг YouTube - <strong class="bb">1 ссылка на 1000 просмотров и получите в подарок 1000 баллов рейтинга за каждую ссылку.</strong>
<br />&nbsp;<br />
Участвует именно ссылка на 1000 просмотров, 10 по 100 не участвуют.<br />
Заказать можно любое количество ссылок по 1000 просмотров и за каждую по 1000 баллов рейтинга. Зачисление баллов будет происходить в ручную.
<br />&nbsp;<br />
Это предложение будет действовать до 2 апреля 10.00 по времени сервера.<br />
Не упустите шанс быстрого карьерного взлета!
<br />&nbsp;<br />
<strong class="bb">С наилучшими пожеланиями, Администрация сайта!</strong> </font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=194#post-18639";s:13:"comments_news";s:1:"0";s:20:"comments_news_status";s:1:"0";s:9:"time_news";s:10:"1554111157";}i:23;a:7:{s:7:"id_news";s:2:"23";s:10:"title_news";s:5:"Акция";s:9:"desc_news";s:1799:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2018/11/28/logo&#46;gif" alt="" /></div>
<br />
<div class="bb" align="center"><font color="#CD2626"><strong class="bb">Добрый вечер, друзья!
<br />&nbsp;<br />
Только 3 дня скидки на рекламу -
<br />&nbsp;<br />
Размещение баннера 728x90 <del class="bb">3.50 </del>руб. = 2.50 руб. в сутки<br />
<strong class="bb">Скидка на Пакет рекламы</strong> № 2 <del class="bb">85 </del>руб. = 68 руб.<br />
<strong class="bb">Скидка на Пакет рекламы</strong> № 3 <del class="bb">120 </del>руб.= 96 руб.</strong></font><br />
</div>
<br />
<div class="bb" align="center"><font color="#CD2626"><strong class="bb">Для пользователей:</strong>
<br />&nbsp;<br />
Просмотр ссылки в серфинге: <strong class="bb">+0.40</strong> балла<br />
Просмотр видеоролика в серфинге YouTube: <strong class="bb">+0.40</strong> балла<br />
Выполнение задания рекламодателя: <strong class="bb">+30.00</strong> баллов<br />
За каждые полные 10 руб. потраченные на пополнение копилки проекта начисляется: <strong class="bb">+180.00</strong> баллов<br />
За каждые полные 10 руб потраченные на оплату рекламы с рекламного счета [кроме оплаты заданий и тестов]: <strong class="bb">+280.00</strong> баллов
<br />&nbsp;<br />
За размещение VIP-ссылки в серфинге: <strong class="bb">+80.00</strong> баллов<br />
За размещения VIP-баннера в серфинге:<strong class="bb"> +80.00</strong> баллов<br />
За размещение VIP-ролика в серфинге YouTube: <strong class="bb">+80.00</strong> баллов </font></div>
<br />
<div class="bb" align="center"><font size="2"><font color="#CD2626"><strong class="bb">Замечательного вечера и приятных выходных дней вам, друзья!</strong>
<br />&nbsp;<br />
<strong class="bb">С уважением, Администрация сайта.</strong></font></font></div>";s:15:"link_forum_news";s:0:"";s:13:"comments_news";s:1:"1";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1553876125";}i:22;a:7:{s:7:"id_news";s:2:"22";s:10:"title_news";s:10:"Обновление";s:9:"desc_news";s:1547:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/03/24/82_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><strong class="bb">Добрый день, уважаемые пользователи!</strong>
<br />&nbsp;<br />
Сообщаем вам, что произошли изменения в заказе безлимитного серфинга.<br />
Теперь просмотр вашей ссылки возможен только 1 раз с одного уникального IP адреса.<br />
В целях выживаемости сайта и привлечения рекламодателей мы пошли на такие меры.<br />
Вашу рекламу будут смотреть только уникальные пользователи.
<br />&nbsp;<br />
Цены на безлимитный серфинг снижены и мы надеемся, что рекламодателям понравятся новые условия заказа и стоимость.<br />
Рекламодатели, будьте внимательны, если вас не устраивают условия заказа с такими настройками,<br />
выбирайте обычный серфинг, где вы сможете выбирать настройки на свое усмотрение.
<br />&nbsp;<br />
Стоимость на данный момент -<br />
 <strong class="bb">1 неделя безлимитного динамического/баннерного серфинга - 150 руб.<br />
 2 недели безлимитного динамического/баннерного серфинга - 210 руб.<br />
 3 недели безлимитного динамического/баннерного серфинга - 280 руб.<br />
 4 недели безлимитного динамического/баннерного серфинга - 415 руб.<br />
Возможно цены будут еще пересмотрены по мере необходимости и в связи с увеличением количества пользователей, в большую или меньшую сторону.</strong>
<br />&nbsp;<br />
<strong class="bb">Спасибо за ваше терпение, понимание и лояльность к нашему проекту!<br />
С уважением, Администрация сайта.</strong></div>";s:15:"link_forum_news";s:0:"";s:13:"comments_news";s:1:"0";s:20:"comments_news_status";s:1:"0";s:9:"time_news";s:10:"1553414265";}i:21;a:7:{s:7:"id_news";s:2:"21";s:10:"title_news";s:5:"Акция";s:9:"desc_news";s:2163:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/03/22/SKORPION2&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="2"><font color="green"><strong class="bb">Добрый вечер, друзья!<br />
Закончилась рабочая неделя, нас ждут выходные дни.<br />
В этот весенний вечер, мы предлагаем вам акцию выходного дня.</strong></font></font></div>
<br />&nbsp;<br />
<font size="2"><font color="#CD2626">Только вечер пятницы, в субботу и воскресенье для вас -
<br />&nbsp;<br />
Просмотр ссылки в серфинге: <strong class="bb">+0.50</strong> балла<br />
Выполнение задания рекламодателя: <strong class="bb">+30.00</strong> баллов<br />
Прохождение теста: <strong class="bb">+3.00</strong> балла<br />
За каждые полные 10 руб. потраченные на пополнение <strong class="bb">копилки</strong> проекта начисляется: <strong class="bb">+200.00</strong> баллов<br />
За каждые полные 10 руб потраченные на оплату рекламы с рекламного счета [кроме оплаты заданий и тестов]: <strong class="bb">+300.00</strong> баллов
<br />&nbsp;<br />
За размещение VIP-ссылки в серфинге: <strong class="bb">+70.00</strong> баллов<br />
За размещения VIP-баннера в серфинге: <strong class="bb">+70.00</strong> баллов<br />
За размещение VIP-ролика в серфинге YouTube: <strong class="bb">+70.00</strong> баллов
<br />&nbsp;<br />
<strong class="bb">Скидка на заказ безлимитного серфинга/баннерного серфинга на 1 неделю</strong> <del class="bb">210 </del>руб. = 150 руб.<br />
<strong class="bb">Скидка на Пакеты рекламы</strong> № 2 <del class="bb">85 </del>руб. = 68 руб.<br />
<strong class="bb">Скидка на Пакеты рекламы</strong> № 3 <del class="bb">120 </del>руб.= 96 руб.<br />
<strong class="bb">Бегущая строка</strong> - <strong class="bb">1 руб.</strong> в сутки<br />
<strong class="bb">Баннер 468х60</strong> - <strong class="bb">2 руб.</strong> в сутки.</font></font>
<br />&nbsp;<br />
<div class="bb" align="center"><font size="2"><font color="green"><strong class="bb">Замечательного вечера и приятных выходных дней вам, друзья!</strong>
<br />&nbsp;<br />
<strong class="bb">С уважением, Администрация сайта.</strong></font></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=193#post-18335";s:13:"comments_news";s:1:"0";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1553269633";}i:20;a:7:{s:7:"id_news";s:2:"20";s:10:"title_news";s:11:"Тех.работы.";s:9:"desc_news";s:691:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/01/09/590d93c8_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="2"><font color="#0000FF"><strong class="bb">Здравствуйте, уважаемые пользователи!
<br />&nbsp;<br />
Сообщаем вам, что 13 марта с 00.00 часов, на нашем хостинге будут производиться технические работы.<br />
Поэтому на период этих работ наш сайт будет недоступен.<br />
По завершении работ, сайт будет работать в прежнем режиме.
<br />&nbsp;<br />
Приносим извинения за доставленные неудобства!<br />
Надеемся на ваше понимание и терпение.
<br />&nbsp;<br />
С уважением, Администрация сайта!</strong></font></font></div>";s:15:"link_forum_news";s:0:"";s:13:"comments_news";s:1:"0";s:20:"comments_news_status";s:1:"0";s:9:"time_news";s:10:"1552391539";}i:19;a:7:{s:7:"id_news";s:2:"19";s:10:"title_news";s:17:"Воскресная акция.";s:9:"desc_news";s:1779:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/03/10/76b3dbad_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="3"><font color="993399"><strong class="bb">Воскресное предложение - Выгода!</strong></font></font></div>
<br />
<div class="bb" align="center"><font color="993399"><strong class="bb">Добрый день друзья!<br />
Специально для вас, в этот день - выгодное предложение -</strong></font></div>
<br />
<div class="bb" align="center"><font color="#008B8B"><strong class="bb">Закажите динамический или баннерный серфинг от 3000 просмотров по 5 сек. и более - бонус от нас:<br />
размещение вашей ссылки динамического серфинга на 1000 просмотров по 5 сек. на двух других наших проектах - БЕСПЛАТНО!</strong>
<br />&nbsp;<br />
<strong class="bb"><i class="bb">В результате ваша ссылка будет на 3 наших сайтах - ScorpionBux.info, AngelBux.info, Supreme-garden.ru</i></strong>
<br />&nbsp;<br />
<strong class="bb">При заказе 3 ссылок по данной акции, в подарок от нас 1500 просмотров ваших ссылок по 5 сек.</strong>( за каждую ссылку бонусные показы)
<br />&nbsp;<br />
<i class="bb"><strong class="bb">После заказа, пришлите ссылку по внутренней почте на логин Znata.<br />
В акции участвую ссылки заказанные в период проведения акции (сразу после выхода новостей) и оплаченные с внешних платежных систем.</strong></i></font></div>
<br />
<div class="bb" align="center"><font color="993399"><strong class="bb">Рекламируйте с выгодой для себя!<br />
Предложение разовое, и будет действовать только до 17 марта.
<br />&nbsp;<br />
Так же напоминаем, что праздничная акция закончится через 4 часа.
<br />&nbsp;<br />
Приятного воскресного вечера!
<br />&nbsp;<br />
С уважением, Администрация сайта.</strong></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=191#post-18015";s:13:"comments_news";s:1:"1";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1552217207";}i:18;a:7:{s:7:"id_news";s:2:"18";s:10:"title_news";s:13:"С праздником!";s:9:"desc_news";s:3232:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/03/07/43e2b34e_l&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font color="red"><strong class="bb">Дорогие женщины, вы — нежные, прекрасные цветы, которые украшают наш мир! <br />
В этот замечательный мартовский день желаем вам уверенности в своих силах, внешней обаятельности, внутреннего магнетизма, целеустремленности и жизнестойкости. <br />
Пускай вам будут подвластны самые непростые задания, сложные проекты, вы принимаете правильные решения, сохраняете гармонию и баланс!<br />
С праздником вас!</strong></font></div>
<br />
<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/02/13/cveta-1171&#46;gif" alt="" /></div>
<br />
<font color="green"><strong class="bb">8 марта у нас двойной праздник</strong> - Международный женский день 8 марта и 2 месяца нашему проекту!<br />
Поздравляем наших милых девушек и всех пользователей проекта с этими замечательными событиями!
<br />&nbsp;<br />
Бонусы и подарки от Администрации сайта -
<br />&nbsp;<br />
За ежедневную активность: <strong class="bb">+50.00</strong> баллов<br />
Просмотр ссылки в серфинге: <strong class="bb">+0.50</strong> балла<br />
Просмотр видеоролика в серфинге YouTube: <strong class="bb">+0.50</strong> балла<br />
Выполнение задания рекламодателя: <strong class="bb">+50.00</strong> баллов<br />
Привлечение реферала: <strong class="bb">+50.00</strong> баллов<br />
За каждые полные 10 руб. Потраченные на пополнение копилки проекта начисляется: <strong class="bb">+160.00 </strong>баллов<br />
За каждое размещение аватара на доске почёта: <strong class="bb">+25.00 </strong>балла<br />
За каждые полные 10 руб потраченные на оплату рекламы с рекламного счета [кроме оплаты заданий]: <strong class="bb">+150.00</strong> баллов<br />
За размещение VIP-ссылки в серфинге: <strong class="bb">+250.00</strong> баллов<br />
За размещения VIP-баннера в серфинге: <strong class="bb">+250.00 </strong>баллов<br />
За размещение VIP-ролика в серфинге YouTube: <strong class="bb">+250.00</strong> баллов
<br />&nbsp;<br />
Размещение баннеров всех размеров по <strong class="bb">1.50 руб.</strong> в сутки
<br />&nbsp;<br />
Дополнительный <strong class="bb">бонус 10000 баллов рейтинга</strong> за каждую ссылку, вы можете получить после заказа безлимитного динамического серфинга на 1 месяц.<br />
Действие акции начнется после выхода новостей.<br />
В акции участвуют ссылки безлимитного серфинга или баннерного безлимитного серфинга на месяц и заказанные в период проведения акции.
<br />&nbsp;<br />
Игра на форуме - <strong class="bb">Найдите цветок и получите баллы рейтинга в подарок!</strong><br />
<a href="https://scorpionbux.info/forum.php&#063;th=189#post-17926" target="_blank">https://scorpionbux.info/forum.php&#063;th=189#post-17926</a>
<br />&nbsp;<br />
<i class="bb">Акция закончится 10 марта в 18.00 по времени сервера.</i></font>
<br />&nbsp;<br />
<div class="bb" align="center"><font color="red"><strong class="bb">Желаем счастья и любви — они дороже всех подарков! <br />
И пусть все сбудутся мечты в прекрасный день 8 марта!
<br />&nbsp;<br />
С наилучшими пожеланиями, Администрация сайта!</strong></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=190#post-17927";s:13:"comments_news";s:1:"1";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1551961005";}i:17;a:7:{s:7:"id_news";s:2:"17";s:10:"title_news";s:13:"Весна пришла!";s:9:"desc_news";s:2323:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/03/01/SKORPION2&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="2"><font color="#551A8B"><strong class="bb">С наступлением весны, друзья!</strong>
<br />&nbsp;<br />
<strong class="bb">С Первым днём весны прекрасной!<br />
Пусть она подарит счастье,<br />
Прорастит успехов много,<br />
Укрепит ими дорогу.
<br />&nbsp;<br />
Как подснежником чудесным,<br />
Жизнь украсит теплотой,<br />
И весенним солнцем нежным<br />
Освещает день любой.
<br />&nbsp;<br />
Пусть уйдёт печаль со снегом —<br />
Смоет талая вода,<br />
И придёт ей на замену<br />
Мир, любовь и доброта!</strong></font></font></div>
<br />
<div class="bb" align="center"><font color="000099"><strong class="bb">Только до 3 марта 18.00 по времени сервера для вас:</strong></font></div>
<br />
<font color="000099">Выполнение задания рекламодателя: <strong class="bb">+25.00</strong> баллов<br />
Привлечение реферала: <strong class="bb">+40.00</strong> баллов<br />
За размещение VIP-ссылки в серфинге: <strong class="bb">+210.00</strong> баллов<br />
За размещения VIP-баннера в серфинге: <strong class="bb">+210.00</strong> баллов<br />
За размещение VIP-ролика в серфинге YouTube: <strong class="bb">+210.00</strong> баллов<br />
</font>
<br />&nbsp;<br />
<font color="#551A8B"><i class="bb">Дополнительный <strong class="bb">бонус 3000 баллов рейтинга за каждую ссылку</strong>, вы <strong class="bb">можете получить после заказа безлимитного динамического серфинга на 1 месяц</strong>.<br />
Действие акции начнется после выхода новостей.<br />
В акции участвуют ссылки безлимитного серфинга или баннерного безлимитного серфинга на месяц и заказанные в период проведения акции. <br />
Так же <strong class="bb">за заказ безлимитного серфинга YouTube на 1 месяц</strong> - <strong class="bb">бонус 2000 баллов рейтинга</strong>.
<br />&nbsp;<br />
<strong class="bb">За размещение Оплачиваемых посещений на сумму 100 руб. и более - бонус 1500 баллов рейтинга.</strong>
<br />&nbsp;<br />
Не упустите шанс поднять свой рейтинг до 3 марта.<br />
</i></font><br />
<div class="bb" align="center"><font color="#551A8B"><strong class="bb">Отличного вам весеннего настроения!
<br />&nbsp;<br />
С уважением, Администрация сайта!</strong></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=187#post-17701";s:13:"comments_news";s:1:"3";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1551430331";}i:16;a:7:{s:7:"id_news";s:2:"16";s:10:"title_news";s:12:"Поздравляем!";s:9:"desc_news";s:2444:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/02/20/SKORPION&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="2"><font color="red"><strong class="bb">Дорогие наши мужчины, наши храбрые и отважные защитники! <br />
Вы наша опора, надежда и защита! <br />
Поздравляем вас с Днем защитника Отечества! <br />
Дорогие, любимые, родные, спасибо вам за смелость, ответственность и надежность. <br />
Мы ценим всё, что вы для нас делаете, и очень гордимся вами, ведь за вашими широкими спинами нам нечего бояться! <br />
Желаем вам, наши смелые, заботливые и любимые мужчины, крепкого здоровья, удачи во всём, сил, терпения и мужественности. <br />
Будьте всегда такими сильными и храбрыми. <br />
Счастья, любви, благополучия и, конечно же, мирного неба над головой желаем вам и вашим семьям!</strong></font></font></div>
<br />
<div class="bb" align="center"><font size="2"><font color="red"> <strong class="bb">В честь этого замечательного праздника - бонусы:</strong></font></font></div>
<br />&nbsp;<br />
<font size="2"><font color="#556B2F">Просмотр ссылки в серфинге: <strong class="bb">+0.40</strong> балла<br />
Просмотр видеоролика в серфинге YouTube: <strong class="bb">+0.40</strong> балла<br />
Выполнение задания рекламодателя: <strong class="bb">+45.00</strong> баллов<br />
За каждые полные 10 руб. Потраченные на пополнение копилки проекта начисляется: <strong class="bb">+150.00</strong> баллов<br />
За каждое размещение аватара на доске почёта: <strong class="bb">+50.00</strong> баллов<br />
За каждые полные 10 руб потраченные на оплату рекламы с рекламного счета [кроме оплаты заданий]: <strong class="bb">+150.00</strong> баллов<br />
За размещение VIP-ссылки в серфинге: <strong class="bb">+300.00</strong> баллов<br />
За размещения VIP-баннера в серфинге:<strong class="bb"> +300.00</strong> баллов<br />
За размещение VIP-ролика в серфинге YouTube: <strong class="bb">+300.00</strong> баллов
<br />&nbsp;<br />
<i class="bb">За заказ безлимитного серфинга/баннерного серфинга на 3 недели <del class="bb">700 </del>руб. = 350 р.<br />
За заказ безлимитного серфинга/баннерного серфинга на 4 недели <del class="bb">900 </del>руб. = 630 р.</i></font></font>
<br />&nbsp;<br />
<div class="bb" align="center"><font size="2"><font color="red"><strong class="bb">Отличного вам настроения!<br />
С наилучшими пожеланиями, Администрация сайта!</strong></font></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=186#post-17459";s:13:"comments_news";s:1:"4";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1550847755";}i:15;a:7:{s:7:"id_news";s:2:"15";s:10:"title_news";s:18:"Скидки на безлимит";s:9:"desc_news";s:859:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/02/19/4e2763e5_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="3"><font color="#8B0000"><strong class="bb">Добрый вечер, друзья!</strong><br />
- Да, сегодня у нас скидки!<br />
Действуют до 23 февраля - снижены цены на безлимитный серфинг.
<br />&nbsp;<br />
<i class="bb">За заказ безлимитного серфинга/баннерного серфинга на 3 недели <del class="bb">700 </del>руб. = 350 р.<br />
За заказ безлимитного серфинга/баннерного серфинга на 4 недели <del class="bb">900 </del>руб. = 630 р.</i>
<br />&nbsp;<br />
<strong class="bb">Воспользуйтесь нашим предложением для продвижения ваших проектов по сниженным ценам!
<br />&nbsp;<br />
Всех благ и отличного вам настроения!
<br />&nbsp;<br />
С уважением, Администрация сайта.</strong></font></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=185#post-17322";s:13:"comments_news";s:1:"1";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1550584696";}i:14;a:7:{s:7:"id_news";s:2:"14";s:10:"title_news";s:10:"Тех.работы";s:9:"desc_news";s:612:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/01/09/590d93c8_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><strong class="bb">Здравствуйте, уважаемые пользователи!
<br />&nbsp;<br />
По техническим причинам мы вынуждены уйти на тех.работы на нашем сервере в 00.00. часов по МСК 17 февраля.<br />
Приносим свои извинения за доставленные неудобства!<br />
По завершению работ через несколько часов, сайт будет работать в обычном режиме.
<br />&nbsp;<br />
Надеемся на ваше терпение и понимание!
<br />&nbsp;<br />
С уважением, Администрация сайта!</strong></div>";s:15:"link_forum_news";s:0:"";s:13:"comments_news";s:1:"0";s:20:"comments_news_status";s:1:"0";s:9:"time_news";s:10:"1550289622";}i:13;a:7:{s:7:"id_news";s:2:"13";s:10:"title_news";s:18:"С днем влюбленных!";s:9:"desc_news";s:3913:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/02/13/SKORPION&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="3"><font color="red"><strong class="bb">Дорогие друзья!
<br />&nbsp;<br />
Поздравляем с Днем святого Валентина! С днём влюбленных!<br />
Желаем провести праздник - так весело, чтобы было трудно встать с утра; так романтично, чтобы рассказывать в старости внукам; так страстно, чтобы пылать как огонь. <br />
Достойных половинок, прекрасных признаний, судьбоносных решений, откровенных сюрпризов, долгожданных новостей. <br />
Любите искренне, каждой частичкой души, не обижайте, прощайте.</strong></font></font></div>
<br />
<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/02/13/cveta-1171&#46;gif" alt="" /></div>
<br />
<font size="2"><font color="green"><strong class="bb">Начнем праздновать сегодня, чтобы уже сегодня было ощущение праздника.<br />
с 13 по 21 февраля до 19.00 по времени сервера -</strong>
<br />&nbsp;<br />
<strong class="bb">для пользователей:</strong>
<br />&nbsp;<br />
Выполнение задания рекламодателя: <strong class="bb">+35.00 балла</strong><br />
За каждые полные 10 руб. Потраченные на пополнение копилки проекта начисляется: <strong class="bb">+150.00 баллов</strong><br />
За каждое размещение аватара на доске почёта: <strong class="bb">+30.00 </strong>балла<br />
За каждые полные 10 руб потраченные на оплату рекламы с рекламного счета: <strong class="bb">+150.00 баллов</strong><br />
За размещение VIP-ссылки в серфинге: <strong class="bb">+250.00 баллов</strong><br />
За размещения VIP-баннера в серфинге: <strong class="bb">+250.00 баллов</strong><br />
За размещение VIP-ролика в серфинге YouTube: <strong class="bb">+250.00 баллов</strong>
<br />&nbsp;<br />
<strong class="bb">для рекламодателей:</strong>
<br />&nbsp;<br />
За заказ безлимитного VIP серфинга/ баннерного VIP серфинга на 1 неделю <strong class="bb">в подарок бесплатное размещение вашего баннера любого размера на 90 дней.</strong>
<br />&nbsp;<br />
За заказ безлимитного VIP серфинга/ баннерного VIP серфинга на 2 недели <strong class="bb">в подарок бесплатное размещение вашего баннера любого размера на 120 дней.</strong>
<br />&nbsp;<br />
За заказ безлимитного VIP серфинга/ баннерного VIP серфинга на 3 недели в<strong class="bb"> подарок бесплатное размещение вашего баннера любого размера на 150 дней.</strong>
<br />&nbsp;<br />
За заказ безлимитного VIP серфинга/ баннерного VIP серфинга на 4 недели <strong class="bb">в подарок бесплатное размещение вашего баннера любого размера на 250 дней.</strong>
<br />&nbsp;<br />
За заказ динамического серфинга/ баннерного серфинга количеством от 5000 просмотров по 5 сек. и более <strong class="bb">в подарок бесплатное размещение вашего баннера любого размера на 150 дней.</strong>
<br />&nbsp;<br />
Ссылки на баннер пришлите после заказа по внутренней почте на логин Znata и получите свой подарок.
<br />&nbsp;<br />
<strong class="bb">Приглашаем принять участие в игре Ласковый алфавит</strong> - победителю <strong class="bb">приз</strong> - баллы рейтинга и денежка на рекламный счет (подробнее на форуме в разделе Беседка)<br />
<a href="https://scorpionbux.info/forum.php&#063;th=181#post-17013" target="_blank">https://scorpionbux.info/forum.php&#063;th=181#post-17013</a>
<br />&nbsp;<br />
Поднимите свой рейтинг, участвуя в игре - <strong class="bb">Найдите сердечко!</strong> подробности на странице форума <a href="https://scorpionbux.info/forum.php&#063;th=182#post-17014" target="_blank">https://scorpionbux.info/forum.php&#063;th=182#post-17014</a></font></font>
<br />&nbsp;<br />
<div class="bb" align="center"><font size="2"><font color="red"><strong class="bb">Поздравляем вас от души с этим романтичным праздником!</strong>
<br />&nbsp;<br />
<strong class="bb">С уважением, Администрация сайта!</strong></font></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=183#post-17018";s:13:"comments_news";s:1:"4";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1550069306";}i:12;a:7:{s:7:"id_news";s:2:"12";s:10:"title_news";s:5:"Акция";s:9:"desc_news";s:1857:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/02/08/9fbe83c4_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="2"><font color="#8B2500"><strong class="bb">Добрый вечер, друзья!
<br />&nbsp;<br />
Пятница, рабочая неделя закончилась, впереди выходные дни.<br />
Предлагаем вам акцию - Вечер у камина.<br />
Давайте вместе проведем это время возле виртуального камина на нашем сайте в этот зимний вечер..</strong></font></font></div>
<br />
<font size="2"><font color="#8B2500">Только вечер пятницы, в субботу и воскресенье для вас -
<br />&nbsp;<br />
Просмотр ссылки в серфинге: <strong class="bb">+0.50</strong> балла<br />
Выполнение задания рекламодателя: <strong class="bb">+50.00</strong> баллов<br />
Прохождение теста: <strong class="bb">+3.00</strong> балла<br />
За каждые полные 10 руб. потраченные на пополнение <strong class="bb">копилки</strong> проекта начисляется: <strong class="bb">+200.00</strong> баллов<br />
За каждые полные 10 руб потраченные на оплату рекламы с рекламного счета [кроме оплаты заданий]: <strong class="bb">+200.00</strong> баллов
<br />&nbsp;<br />
За размещение VIP-ссылки в серфинге: <strong class="bb">+280.00</strong> баллов<br />
За размещения VIP-баннера в серфинге: <strong class="bb">+280.00</strong> баллов<br />
За размещение VIP-ролика в серфинге YouTube: <strong class="bb">+280.00</strong> баллов
<br />&nbsp;<br />
<strong class="bb">Скидка на заказ безлимитного серфинга/баннерного серфинга на 3 недели</strong> <del class="bb">700 </del>руб. = 400 руб.</font></font>
<br />&nbsp;<br />
<div class="bb" align="center"><font size="2"><font color="#8B2500"><strong class="bb">Замечательного вечера и приятных выходных дней вам, друзья!</strong>
<br />&nbsp;<br />
<strong class="bb">С уважением, Администрация сайта.</strong></font></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=180#post-16769";s:13:"comments_news";s:1:"3";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1549631094";}i:11;a:7:{s:7:"id_news";s:2:"11";s:10:"title_news";s:12:"Нам 1 месяц!";s:9:"desc_news";s:3076:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/02/04/21d942a8_l&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="3"><font color="#551A8B"><strong class="bb">Нам 1 месяц! Завтра 30 день работы нашего сайта.
<br />&nbsp;<br />
Поздравляем друзья, мы в сети уже 1 месяц!</strong></font></font></div>
<br />
<font size="2"><font color="#551A8B"><strong class="bb"><i class="bb">За этот небольшой период времени на сайте -
<br />&nbsp;<br />
Зарегистрировано более 7000 пользователей<br />
выплачено более 36 тыс. рублей<br />
Были конечно и проблемы, которые бывают при старте, сейчас они устранены и мы надеемся на плодотворную работу вместе с вами. <br />
Проект продолжит развиваться во благо всем и мы будем стараться создавать комфортные условия для наших пользователей.</i></strong></font></font>
<br />&nbsp;<br />
<font size="2"><font color="#551A8B"><strong class="bb">В честь нашего праздника:</strong>
<br />&nbsp;<br />
<strong class="bb">Всем снова доступен тест-драйв на 200 просмотров.</strong><br />
Привлечение реферала: <strong class="bb">+50.00 балла</strong><br />
За размещение VIP-ссылки в серфинге: <strong class="bb">+300.00 баллов</strong><br />
За размещения VIP-баннера в серфинге: <strong class="bb">+300.00 баллов</strong><br />
За размещение VIP-ролика в серфинге YouTube: <strong class="bb">+300.00 баллов</strong><br />
За каждые полные 10 руб потраченные на оплату рекламы с рекламного счета [кроме оплаты заданий]: <strong class="bb">+150.00 балла</strong>
<br />&nbsp;<br />
<strong class="bb">Скидка</strong> на Пакеты рекламы № 2, 3 - <strong class="bb">20%</strong><br />
Безлимитный серфинг/баннерный серфинг на 3 недели - <del class="bb">700 руб.</del> = 350 руб. - <strong class="bb">скидка 50%</strong><br />
Статические ссылки - <strong class="bb">2 руб. в сутки</strong><br />
Баннеры 728x90, 200x300 - <strong class="bb">2 руб. в сутки</strong><br />
Баннер 468x60 во фрейме - <strong class="bb">1 руб. в сутки</strong><br />
Ссылки во фрейме - <strong class="bb">скидка 50% - 0.50 в сутки </strong>
<br />&nbsp;<br />
Скидки и праздничные баллы рейтинга будут действительны с момента публикации новости и до 7 февраля 18.00 времени сервера.
<br />&nbsp;<br />
Так же объявляем, что <strong class="bb">пользователь с ID 10000 и реферер пригласивший его</strong> <strong class="bb">получат приз</strong> -<br />
1000 баллов и 10 руб. на рекламный счет пользователю с id 10000, рефереру 2000 баллов рейтинга и 50 руб. на рекламный счет.<br />
В случае, если 10000 пользователь не активирует свой аккаунт и не проявит активность на сайте, призовые условия перейдут следующему пользователю под id 10001 и его рефереру.</font></font>
<br />&nbsp;<br />
<div class="bb" align="center"><font size="3"><font color="#551A8B"><strong class="bb">От всей души благодарим вас за доверие нашему проекту!<br />
Огромная благодарность всем рекламодателям, поверивших в нас!<br />
Спасибо вам, что вы с нами!<br />
С уважением, Администрация сайта ScorpionBux.info!</strong></font></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=178#post-16505";s:13:"comments_news";s:1:"9";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1549298791";}i:10;a:7:{s:7:"id_news";s:2:"10";s:10:"title_news";s:5:"Акция";s:9:"desc_news";s:2710:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/02/01/65cbf2b9_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="3"><font color="000000"><strong class="bb">Здравствуйте, друзья!<br />
Вот и наступил последний месяц зимы, весна все ближе..<br />
А на нашем сайте Акция - Февральский снегопад.</strong></font></font></div>
<br />
<strong class="bb">Для пользователей: </strong><br />
За ежедневную активность: <strong class="bb">+15.00</strong> балла<br />
Просмотр ссылки в серфинге: <strong class="bb">+0.40</strong> балла<br />
Выполнение задания рекламодателя: <strong class="bb">+15.00</strong> балла<br />
Прохождение теста: <strong class="bb">+2.00</strong> балла<br />
За каждые полные 10 руб. потраченные на пополнение копилки проекта начисляется:<strong class="bb"> +150.00</strong> баллов
<br />&nbsp;<br />
<strong class="bb">Для рекламодателей: </strong>
<br />&nbsp;<br />
<strong class="bb">Только 2 и 3 февраля баннеры 468х60 по цене 1 руб. в сутки.</strong>
<br />&nbsp;<br />
Закажите динамический/баннерный серфинг на 5000 просмотров от 10 сек. и более сек.-<br />
<strong class="bb">получите в подарок дополнительно еще 1000 просмотров этой ссылки.</strong>
<br />&nbsp;<br />
Закажите VIP серфинг YouTube на 1000 просмотров и <strong class="bb">получите дополнительно 500 баллов рейтинга + автоматически за заказ еще 250 баллов рейтинга. Итого за заказ 750 баллов.</strong>
<br />&nbsp;<br />
Пополните рекламный счет на 27 руб и закажите автосерфинг на 8000 просмотров по 20 сек. и <strong class="bb">получите в подарок 250 рейтинга </strong>
<br />&nbsp;<br />
Пополните рекламный счет на 15 руб. и создайте один тест - <strong class="bb">получите дополнительно 150 рейтинга</strong>
<br />&nbsp;<br />
Закажите Оплачиваемые посещения на сумму 100 рублей и более-<br />
<strong class="bb">получите дополнительно 800 баллов рейтинга + задание - бонус № 438 от Администрации сайта.</strong>
<br />&nbsp;<br />
О преимуществах оплачиваемых посещений вы можете узнать на этой странице <a href="https://scorpionbux.info/forum.php&#063;th=176#post-16372" target="_blank">https://scorpionbux.info/forum.php&#063;th=176#post-16372</a>
<br />&nbsp;<br />
Акция будет действовать с момента публикации в разделе Новости и до 7 февраля 18.00 по времени сервера.
<br />&nbsp;<br />
<font color="red"><strong class="bb">Бонусы по заказу будут добавлены при условии пополнения рекламного счета через платежные системы и реклама должна быть вновь заказанная, пополнение старых ссылок не участвует в акции.</strong></font>
<br />&nbsp;<br />
<br />
<div class="bb" align="center"><strong class="bb">С уважением, Администрация сайта. </strong></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=177#post-16374";s:13:"comments_news";s:1:"2";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1549017326";}i:9;a:7:{s:7:"id_news";s:1:"9";s:10:"title_news";s:10:"СКИДКА 50%";s:9:"desc_news";s:1299:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/01/24/080b87c6_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="2"><font color="red"><strong class="bb">Здравствуйте, дорогие друзья!
<br />&nbsp;<br />
В последнюю неделю января предоставляем вам возможность продвигать ваши проекты по сниженным ценам.</strong></font></font></div>
<font size="2"><font color="red">
<br />&nbsp;<br />
<strong class="bb">Скидки на рекламу 50% -</strong>
<br />&nbsp;<br />
<i class="bb">Безлимитный серфинг/баннерный серфинг на 1 неделю - <del class="bb">210 руб.</del> = 105 руб.<br />
Безлимитный серфинг/баннерный серфинг на 2 недели - <del class="bb">310 руб.</del> = 155 руб.<br />
Безлимитный серфинг/баннерный серфинг на 3 недели - <del class="bb">700 руб.</del> = 350 руб.<br />
Безлимитный серфинг/баннерный серфинг на 4 недели - <del class="bb">900 руб.</del> = 450 руб.
<br />&nbsp;<br />
Безлимитные оплачиваемые письма на 1 месяц - <del class="bb">250 руб.</del> = 125 руб.<br />
</i></font></font>
<br />&nbsp;<br />
<div class="bb" align="center"><font size="2"><font color="red">Воспользуйтесь нашим предложением и рекламируйте с 50% скидкой!
<br />&nbsp;<br />
<strong class="bb">С уважением, Администрация сайта!</strong></font></font></div>";s:15:"link_forum_news";s:0:"";s:13:"comments_news";s:1:"2";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1548338184";}i:8;a:7:{s:7:"id_news";s:1:"8";s:10:"title_news";s:13:"С праздником!";s:9:"desc_news";s:816:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/01/19/116827835&#46;gif" alt="" /></div>
<br />
<div class="bb" align="center"><font size="3"><font color="#27408B"><strong class="bb">Принимайте поздравления<br />
С днем святым, благословенным —<br />
С Днем Господнего Крещения,<br />
С истинным Богоявлением!
<br />&nbsp;<br />
Пусть сойдет на вас святая<br />
Божья благодать большая,<br />
Небеса оберегают,<br />
Ангел рядом пусть летает.
<br />&nbsp;<br />
Не теряйте веры в то,<br />
Что всё будет хорошо.<br />
Пусть она вам помогает —<br />
На путь верный наставляет!</strong>
<br />&nbsp;<br />
Праздничное предложение - бонус для вас на форуме.
<br />&nbsp;<br />
<strong class="bb">С наилучшими пожеланиями, Администрация сайта ScorpionBux.info!</strong></font></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=171#post-14557";s:13:"comments_news";s:1:"9";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1547887415";}i:7;a:7:{s:7:"id_news";s:1:"7";s:10:"title_news";s:24:"Быстрый карьерный взлет.";s:9:"desc_news";s:1671:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/01/17/34684af4_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="3"><font color="red"><strong class="bb">Дорогие друзья!<br />
Предлагаем вам новую акцию- Быстрый карьерный взлёт.</strong></font></font></div>
<br />
<font size="2"><font color="#0000EE">За заказ - VIP-ссылки в серфинге, VIP-баннера в серфинге, VIP-ролика в серфинге YouTube от 600 просмотров, <strong class="bb">за каждую ссылку получите дополнительно 500 баллов рейтинга.</strong>
<br />&nbsp;<br />
За заказ Оплачиваемых посещений на сумму от 60 руб. получите <strong class="bb">за каждый заказ 600 баллов рейтинга.</strong>
<br />&nbsp;<br />
За заказ Оплачиваемых писем от 2000 просмотров по 15 сек. получите <strong class="bb">за каждый заказ писем 600 баллов рейтинга.</strong></font></font>
<br />&nbsp;<br />
<font size="2"><font color="red"><strong class="bb">Напоминаем, что при этом вы получите автоматическое зачисление баллов за заказ вип серфинга по 100 баллов за каждую ссылку, по 50 баллов за каждые потраченные 10 руб. с рекламного счета и по этой акции будут зачислены в ручную дополнительные баллы рейтинга.</strong>
<br />&nbsp;<br />
Напишите на логин Znata по внутренней почте - тема письма Быстрый взлет<br />
и укажите какой заказ вы сделали, после проверки, вам будут добавлены баллы.<br />
Акция начинается с момента выхода Новостей и продлится с 17 по 20 января 18.00 по МСК.</font></font>
<br />&nbsp;<br />
<div class="bb" align="center"><font size="2"><font color="red"><strong class="bb">С уважением, Администрация сайта ScorpionBux.info!</strong></font></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=168#post-14147";s:13:"comments_news";s:1:"2";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1547716180";}i:6;a:7:{s:7:"id_news";s:1:"6";s:10:"title_news";s:14:"С наступающим!";s:9:"desc_news";s:808:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/01/12/11cac22_l&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="3"><font color="red"><strong class="bb">Со старым Новым годом<br />
Хотим поздравить вас.<br />
Пусть принесет вам праздник<br />
Лишь бодрости запас,<br />
Поднимет настроение,<br />
Удачей одарит,<br />
Избавит от невзгод всех<br />
И всяческих обид!</strong>
<br />&nbsp;<br />
<strong class="bb">Подарки к празднику для наших пользователей на странице форума</strong>
<br />&nbsp;<br />
Праздничного настроения вам, дорогие друзья!</font></font></div>
<br />
<div class="bb" align="center"><font size="2"><font color="red"><strong class="bb">С наилучшими пожеланиями, Администрация сайта ScorpionBux.info!</strong></font></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=168#post-13792";s:13:"comments_news";s:1:"2";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1547308428";}i:5;a:7:{s:7:"id_news";s:1:"5";s:10:"title_news";s:10:"Инвестиции";s:9:"desc_news";s:888:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/01/11/b169d0af_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="2"><font color="#8B1A1A"><strong class="bb">Здравствуйте, дорогие друзья!</strong>
<br />&nbsp;<br />
В наши дни, практический каждый человек задумывался об инвестировании, <br />
сейчас это одна из самых популярных форм для заработка.<br />
Объявляем вам об открытии кабинета инвестора и выпуске акций проекта.<br />
Получение прибыли с акций - один из способов заработка на нашем сайте.<br />
Приглашаем желающих стать партнерами проекта.<br />
Подробности в кабинете Инвестора.<br />
Так же для вас бонус при пополнении баланса.<br />
Всех вам благ и успехов во всех начинаниях!
<br />&nbsp;<br />
<strong class="bb"><i class="bb">С уважением, Администрация сайта ScorpionBux.info.</i></strong></font></font></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=167#post-13712";s:13:"comments_news";s:1:"4";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1547188108";}i:4;a:7:{s:7:"id_news";s:1:"4";s:10:"title_news";s:10:"Тех.работы";s:9:"desc_news";s:813:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/01/09/590d93c8_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="2"><font color="#104E8B"><strong class="bb">Здравствуйте, дорогие друзья!</strong>
<br />&nbsp;<br />
К сожалению, мы вынуждены уйти на технические работы, в связи с переездом на другой сервер.
<br />&nbsp;<br />
Приносим свои глубочайшие извинения за доставленные неудобства!
<br />&nbsp;<br />
Сайт будет недоступен несколько часов (примерно 4-6) с 00.00 по Москве 10 января и до завершения работ.
<br />&nbsp;<br />
Постараемся в кратчайшие сроки вернуться в сеть.
<br />&nbsp;<br />
Надеемся на ваше понимание и терпение.
<br />&nbsp;<br />
<strong class="bb">С уважением, Администрация сайта ScorpionBux.info</strong></font></font></div>";s:15:"link_forum_news";s:0:"";s:13:"comments_news";s:1:"0";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1547053269";}i:3;a:7:{s:7:"id_news";s:1:"3";s:10:"title_news";s:13:"С Рождеством!";s:9:"desc_news";s:1168:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/01/06/f57c8634_l&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="3"><font color="#1874CD"><strong class="bb">Поздравляем с праздником вас!<br />
Пусть Рождество войдет в ваш дом,<br />
С собой неся всё то, что свято!<br />
Пусть будут смех и радость в нём,<br />
От счастья и душа богата!
<br />&nbsp;<br />
Пускай уютом дышит дом,<br />
Пусть ангел вас оберегает!<br />
Мы поздравляем с Рождеством<br />
И только лучшего желаем!</strong>
<br />&nbsp;<br />
<strong class="bb">Праздничная скидка 50% на безлимитную рекламу от Администрации сайта:</strong>
<br />&nbsp;<br />
<i class="bb">Безлимитный серфинг/баннерный серфинг на 3 недели - <del class="bb">700 руб.</del> = 350 руб.<br />
Безлимитный серфинг/баннерный серфинг на 4 недели - <del class="bb">900 руб.</del> = 450 руб.</i>
<br />&nbsp;<br />
Скидки будут действовать до 9 января.
<br />&nbsp;<br />
</font></font><div class="bb" align="center"><font size="3"><font color="#1874CD"><strong class="bb">С наилучшими пожеланиями, Администрация сайта ScorpionBux.info!</strong></font></font></div></div>";s:15:"link_forum_news";s:52:"https://scorpionbux.info/forum.php?th=164#post-13290";s:13:"comments_news";s:1:"3";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1546804574";}i:2;a:7:{s:7:"id_news";s:1:"2";s:10:"title_news";s:24:"Открытие нашего проекта!";s:9:"desc_news";s:655:"<div class="bb" align="center"><img src="https&#58;//kvotka&#46;ru/images/2019/01/04/8273304c_o&#46;jpg" alt="" /></div>
<br />
<div class="bb" align="center"><font size="3"><font color="#8B0A50"><strong class="bb">Здравствуйте, дорогие друзья!<br />
Приветствуем вас на нашем новом проекте!<br />
Мы долго его готовили, и вот сегодня наш долгожданный проект открыт!<br />
Пожелайте нам удачи, успехов и процветания!<br />
Для вас в честь открытия мы подготовили сюрпризы!<br />
На странице форума подробности о подарках на наш праздник!
<br />&nbsp;<br />
<i class="bb">С уважением, Администрация сайта ScorpionBux.info! </i></strong></font></font></div>";s:15:"link_forum_news";s:57:"https://scorpionbux.info/forum.php?th=162&p=-1#post-13252";s:13:"comments_news";s:2:"12";s:20:"comments_news_status";s:1:"1";s:9:"time_news";s:10:"1546758049";}}